version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: 'redis-cache'
    environment:
      - REDIS_PASSWORD=erdeniz123
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
      - app-tier
volumes:
  redis_data:
    driver: local